// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POC.Entities.DbContexts;

#nullable disable

namespace POC.Entities.Migrations.MySql
{
    [DbContext(typeof(OptimiserMySqlDbContext))]
    partial class OptimiserMySqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("POC.Entities.Criteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("TrialId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("enum('Inclusion','Exclusion','Mainevent')");

                    b.HasKey("Id")
                        .HasName("trial_pkey");

                    b.HasIndex("TrialId");

                    b.HasIndex("Type", "TrialId")
                        .IsUnique()
                        .HasDatabaseName("unique_mysql_criteria_trial_id_criteria_type");

                    b.ToTable("Criterion");
                });

            modelBuilder.Entity("POC.Entities.Trial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Trials");
                });

            modelBuilder.Entity("POC.Entities.Criteria", b =>
                {
                    b.HasOne("POC.Entities.Trial", "Trial")
                        .WithMany("Criterion")
                        .HasForeignKey("TrialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trial");
                });

            modelBuilder.Entity("POC.Entities.Trial", b =>
                {
                    b.Navigation("Criterion");
                });
#pragma warning restore 612, 618
        }
    }
}
